### ISSUE TITLE
Rake task 'gettext:po' silently fails on Windows

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/gettext-setup-gem#12]
Problem:
I was attempting to run the gettext-setup gem on Windows against Puppet.  This works succesfully on Mac, Linux and Windows Subsystem for Linux, however on native windows it gives the following message;
```
POT file locales/puppet.pot has been updated
```
However the file is not created and the message comes back VERY quickly.  Running procmon, it is obvious that no files are being parsesd.

After digging around I found the problem is related to the following code;
https://github.com/puppetlabs/gettext-setup-gem/blob/master/lib/tasks/gettext.rake#L36-L41

Firstly I thought the command line was too long (it's MASSIVE for Puppet), However I made the following change;
From
```
           "#{files_to_translate.join(" ")}")
```
To
```
           "#{files_to_translate[0..1].join(" ")}")
```
Just to get the first two files and I received the following error (local git repo is at C:\Source\brannan-puppet);
```
C:/Source/brannan-puppet/.bundle/windows/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:229:in `check_command_line_options': no input files (ArgumentError)
        from C:/Source/brannan-puppet/.bundle/windows/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:149:in `run'
        from C:/Source/brannan-puppet/.bundle/windows/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:34:in `run'
        from C:/Source/brannan-puppet/.bundle/windows/ruby/2.3.0/gems/gettext-3.2.2/bin/rxgettext:24:in `<top (required)>'
        from C:/Source/brannan-puppet/.bundle/windows/ruby/2.3.0/bin/rxgettext:22:in `load'
        from C:/Source/brannan-puppet/.bundle/windows/ruby/2.3.0/bin/rxgettext:22:in `<main>'
POT file locales/puppet.pot has been updated
```

It appears that this gem does not work on Windows.

**Comment by glennsarti** [comment]
Note - Running the same command outside of Ruby's `system` works correctly. e.g.

```
bundle exec rxgettext -o locales/puppet.pot --no-wrap --sort-by-file --no-location --add-comments --msgid-bugs-address '' --package-name '' --package-version '' --copyright-holder='' --copyright-year=2016 lib/hiera/puppet_function.rb lib/hiera/scope.rb
```

generates a correct `pot` file

**Comment by smcclellan** [comment]
@glennsarti Some changes have been made to how the gem interprets return codes for executables. Could you verify that this issue is still existent?

**Comment by smcclellan** [comment]
Just a thought, but using options in this style might work (containing both Windows and Linux path extensions)?

```
  source_files:
    - 'app.rb'
    - 'lib/**/*.rb'
    - 'lib\\**\\*.rb'
```
