### ISSUE TITLE
getting the following error since the last update

### ISSUE THREAD

**Issue by b4ldr** [puppetlabs/gettext-setup-gem#32]
rake aborted!
LoadError: cannot load such file -- gettext-setup
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/semantic_puppet-0.1.4/lib/semantic_puppet.rb:1:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/semantic_puppet-0.1.4/lib/semantic_puppet.rb:1:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/pops.rb:20:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/pops.rb:20:in `<module:Pops>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/pops.rb:12:in `<module:Puppet>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/pops.rb:1:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/parser/compiler.rb:8:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/parser/compiler.rb:8:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/parser.rb:5:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet/parser.rb:5:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet.rb:332:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-4.9.4-universal-darwin/lib/puppet.rb:332:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/templates.rb:2:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/templates.rb:2:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax.rb:3:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax.rb:3:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/tasks/puppet-syntax.rb:1:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/tasks/puppet-syntax.rb:1:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppetlabs_spec_helper-2.1.1/lib/puppetlabs_spec_helper/rake_tasks.rb:452:in `require'
/Users/john.bond/.rvm/gems/ruby-2.3.0/gems/puppetlabs_spec_helper-2.1.1/lib/puppetlabs_spec_helper/rake_tasks.rb:452:in `<top (required)>'
/Users/john.bond/git/puppet-dns/Rakefile:1:in `require'
/Users/john.bond/git/puppet-dns/Rakefile:1:in `<top (required)>'
/Users/john.bond/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/john.bond/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by b4ldr** [comment]
duplicate of #33
