### ISSUE TITLE
Release 0.19 doesn't work for me

### ISSUE THREAD

**Issue by irgeek** [puppetlabs/gettext-setup-gem#33]
Hi folks,

I was updating some gems today and it looks like you released 0.19 right in the middle of what I was doing. If I use that version, however, I can no longer run my Puppet modules rake tests and get the following error:

```
rake aborted!
LoadError: cannot load such file -- gettext-setup
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_puppet-0.1.4/lib/semantic_puppet.rb:1:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/semantic_puppet-0.1.4/lib/semantic_puppet.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/pops.rb:20:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/pops.rb:20:in `<module:Pops>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/pops.rb:12:in `<module:Puppet>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/pops.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/parser/compiler.rb:8:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/parser/compiler.rb:8:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/parser.rb:5:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet/parser.rb:5:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet.rb:332:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-4.9.4/lib/puppet.rb:332:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/templates.rb:2:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/templates.rb:2:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax.rb:3:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax.rb:3:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/tasks/puppet-syntax.rb:1:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppet-syntax-2.4.0/lib/puppet-syntax/tasks/puppet-syntax.rb:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/puppetlabs_spec_helper-2.1.1/lib/puppetlabs_spec_helper/rake_tasks.rb:452:in `require'
/usr/local/lib/ruby/gems/2.3.0/gems/puppetlabs_spec_helper-2.1.1/lib/puppetlabs_spec_helper/rake_tasks.rb:452:in `<top (required)>'
/Users/jsinclair/Development/Shine/aem-upgrade/puppet-simianarmy/Rakefile:1:in `require'
/Users/jsinclair/Development/Shine/aem-upgrade/puppet-simianarmy/Rakefile:1:in `<top (required)>'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
/usr/local/bin/rake:22:in `load'
/usr/local/bin/rake:22:in `<main>'
```

The module in question is [here](https://github.com/shinesolutions/puppet-simianarmy). [Tests](https://travis-ci.org/shinesolutions/puppet-simianarmy) are currently working. If you remove [line 13](https://github.com/shinesolutions/puppet-simianarmy/blob/master/Gemfile#L13) from the Gemfile, and re-run the tests, you get the error above.

Let me know if you need any additional information from me.

**Comment by b4ldr** [comment]
the 0.20.0 version fixed things for me

**Comment by smcclellan** [comment]
0.20 should be the fix for this. Closing in the meantime.
