### ISSUE TITLE
GettextSetup.update_pot exits with 0 on failure

### ISSUE THREAD

**Issue by joshcooper** [puppetlabs/gettext-setup-gem#38]
```
$ git clone https://github.com/puppetlabs/puppet
$ cd puppet
$ git checkout 8e8866b
$ bundle install --path .bundle
$ bundle exec rake gettext:update_pot
/Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/po_entry.rb:305:in `format': This POEntry is a kind of plural but the msgid_plural property is nil. msgid: Function lookup() did not find a value for the name '%{name}' (GetText::POEntry::NoMsgidPluralError)
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/po_entry.rb:175:in `to_s'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/po.rb:210:in `block in to_s'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/po.rb:208:in `each'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/po.rb:208:in `to_s'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:222:in `generate_pot'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:151:in `run'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/lib/gettext/tools/xgettext.rb:34:in `run'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/gems/gettext-3.2.2/bin/rxgettext:24:in `<top (required)>'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/bin/rxgettext:23:in `load'
        from /Users/josh/work/puppet/.bundle/ruby/2.3.0/bin/rxgettext:23:in `<main>'
POT creation failed
$ echo $?
0
```

Although POT creation fails, it exits 0, so CI doesn't think any changes are necessary. Changing the following line causes it to correctly exit with 1, but I don't know if that is sufficient in all cases where failure may occur?

```ruby
        result = GettextSetup::Pot.generate_new_pot(locales_path, path)
        if !result
          puts 'POT creation failed'
          exit 1
```

**Comment by joshcooper** [comment]
Filed as https://tickets.puppetlabs.com/browse/INTL-27, closing github issue
